export const baseTasks = [
  {
    id: 1,
    title: 'Топ 10 лучших рок групп африки',
    description:
      'В статье должны быть группы, которые играют тяжёлую музыку и живут в африке. Показать в статье клипы этих групп и описание их фишек. ',
    status: 'DISTRIBUTED',
    fee: 150,
    dateEnd: '2022-05-28T00:00:00.000Z',
    author: 8,
    article: 2,
    editor: 1,
    editorRef: {
      id: 1,
      firstName: 'Anton',
      lastName: 'Dzhigurda',
      roleName: 'Администратор',
    },
    authorRef: {
      id: 8,
      firstName: 'Kirill',
      lastName: 'Akimov',
      roleName: 'Журналист',
    },
    articleRef: {
      id: 2,
      title: 'Новый клип MADFORS — честный разговор о принятии себя',
      verticalSmallImage: 'images/normal/2.hs.png',
      squareImage: 'images/normal/2.sq.png',
      createdAt: 1652273637136,
      author: 3,
      status: 'CREATED',
    },
    history: [
      {
        id: 8,
        task: 1,
        date: 1652007601098,
        user: 8,
        status: 'CREATED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 1,
        date: 1652008509366,
        user: 8,
        status: 'CREATED',
        comment: 'Установлен новый гонорар',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 1,
        date: 1652008786547,
        user: 8,
        status: 'CREATED',
        comment: 'Задание было переданно другому редактору',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 1,
        date: 1652034022123,
        user: 1,
        status: 'CREATED',
        comment: 'Задание изменено',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652034208483,
        user: 1,
        status: 'CREATED',
        comment: 'Автор был изменён',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652034208487,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-22',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652035089307,
        user: 1,
        status: 'CANCELED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652035256849,
        user: 1,
        status: 'ARCHIVED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652035416633,
        user: 1,
        status: 'CANCELED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652035573248,
        user: 1,
        status: 'ARCHIVED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055176544,
        user: 1,
        status: 'CREATED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055190640,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-23',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055190643,
        user: 1,
        status: 'CREATED',
        comment: 'Установлен новый гонорар',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055197357,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-22',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055296212,
        user: 1,
        status: 'CREATED',
        comment: 'Задание изменено',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652055617468,
        user: 1,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 8,
        task: 1,
        date: 1652055626246,
        user: 8,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 1,
        date: 1652087367564,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 1,
        date: 1652087994804,
        user: 1,
        status: 'CREATED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652088398752,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-28',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652088933339,
        user: 1,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652090094954,
        user: 1,
        status: 'CREATED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 1,
        date: 1652090996735,
        user: 1,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 8,
        task: 1,
        date: 1652091678315,
        user: 8,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 1,
        date: 1652103681697,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 1,
        date: 1652103684867,
        user: 8,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 1,
        date: 1653228836618,
        user: 1,
        status: 'DISTRIBUTED',
        comment: 'Была закреплена статья',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
    ],
  },
  {
    id: 2,
    title: 'Интервью с группой OLIMP ',
    description:
      'Основная идея, получение информации о планах группы на крупный фестиваль Эммаус',
    status: 'ENDED',
    fee: 150,
    dateEnd: '2022-05-28T00:00:00.000Z',
    author: 1,
    article: 1,
    editor: 1,
    editorRef: {
      id: 1,
      firstName: 'Anton',
      lastName: 'Dzhigurda',
      roleName: 'Администратор',
    },
    authorRef: {
      id: 1,
      firstName: 'Anton',
      lastName: 'Dzhigurda',
      roleName: 'Администратор',
    },
    articleRef: {
      id: 1,
      title: 'Новый клип MADFORS — честный разговор о принятии себя',
      verticalSmallImage: 'images/normal/1.hs.png',
      squareImage: 'images/normal/1.sq.png',
      createdAt: 1652114472481,
      author: 1,
      status: 'CREATED',
    },
    history: [
      {
        id: 8,
        task: 2,
        date: 1652008881990,
        user: 8,
        status: 'CREATED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652008892277,
        user: 8,
        status: 'CREATED',
        comment: 'Установлен новый гонорар',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652008928156,
        user: 8,
        status: 'CREATED',
        comment: 'Была закреплена статья',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652009744533,
        user: 8,
        status: 'CREATED',
        comment: 'Задание изменено',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652010805178,
        user: 8,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-09',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652010813208,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652010829319,
        user: 8,
        status: 'CREATED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652010839836,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652011552426,
        user: 8,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652011563292,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652011734248,
        user: 8,
        status: 'PUBLISHED',
        comment: 'Автор был изменён',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652011776576,
        user: 8,
        status: 'CREATED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 2,
        date: 1652011784484,
        user: 1,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 8,
        task: 2,
        date: 1652038642201,
        user: 8,
        status: 'CANCELED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652040279782,
        user: 8,
        status: 'ARCHIVED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 2,
        date: 1652273676385,
        user: 1,
        status: 'CREATED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273730066,
        user: 1,
        status: 'CREATED',
        comment: 'Задание изменено',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273734085,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-25',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273734089,
        user: 1,
        status: 'CREATED',
        comment: 'Установлен новый гонорар',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273743262,
        user: 1,
        status: 'CREATED',
        comment: 'Дата сдачи задания изменена на 2022-05-28',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273757458,
        user: 1,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 8,
        task: 2,
        date: 1652273807660,
        user: 8,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 8,
        task: 2,
        date: 1652273861871,
        user: 8,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Kirill',
        lastName: 'Akimov',
        roleName: 'Журналист',
      },
      {
        id: 1,
        task: 2,
        date: 1652273868047,
        user: 1,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1652273965104,
        user: 1,
        status: 'PUBLISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1653228845321,
        user: 1,
        status: 'DISTRIBUTED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1653228856171,
        user: 1,
        status: 'DISTRIBUTED',
        comment: 'Была закреплена статья',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1653228857948,
        user: 1,
        status: 'PENDING_RESOLVE',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1653228858568,
        user: 1,
        status: 'FINISHED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
      {
        id: 1,
        task: 2,
        date: 1653228861865,
        user: 1,
        status: 'ENDED',
        comment: '',
        firstName: 'Anton',
        lastName: 'Dzhigurda',
        roleName: 'Администратор',
      },
    ],
  },
];
